/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    clients: ClientAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    projects: Project;
    categories: Category;
    faqs: Faq;
    media: Media;
    inquiries: Inquiry;
    'line-replies': LineReply;
    'line-sessions': LineSession;
    users: User;
    clients: Client;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'line-replies': LineRepliesSelect<false> | LineRepliesSelect<true>;
    'line-sessions': LineSessionsSelect<false> | LineSessionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh' | 'en') | ('zh' | 'en')[];
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'process-page': ProcessPage;
    'contact-page': ContactPage;
    'site-settings': SiteSetting;
    'line-settings': LineSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'process-page': ProcessPageSelect<false> | ProcessPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'line-settings': LineSettingsSelect<false> | LineSettingsSelect<true>;
  };
  locale: 'zh' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Client;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ClientAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * 首頁服務卡片與列表頁使用
   */
  summary: string;
  cover?: (number | null) | Media;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  problem?: string | null;
  solution?: string | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  points?:
    | {
        title: string;
        description?: string | null;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  addons?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 服務頁會自動列出這些分類底下的作品
   */
  relatedCategories?: (number | Category)[] | null;
  /**
   * 網址用的英文代稱，例如 brand-website
   */
  slug: string;
  /**
   * 數字小的排前面
   */
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 描述圖片內容，給螢幕閱讀器與 Google 看
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * 例如 brand-website
   */
  slug: string;
  /**
   * 數字小的排前面
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  category: number | Category;
  siteType?: string | null;
  industry?: string | null;
  url?: string | null;
  year?: number | null;
  summary?: string | null;
  tech?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 跑馬燈大方塊與案例封面，從頁面最上方截
   */
  cover?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  mobileShot?: (number | null) | Media;
  /**
   * 網址用的英文代稱，例如 brand-website
   */
  slug: string;
  /**
   * 數字小的排前面
   */
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * 數字小的排前面
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  lineId?: string | null;
  source?: ('web' | 'line') | null;
  lineUserId?: string | null;
  service?: string | null;
  budget?: string | null;
  message: string;
  /**
   * 表單上「存到詢問單的：其他」欄位的回答
   */
  extras?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('new' | 'contacted' | 'quoted' | 'won' | 'lost') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 客人傳來的訊息包含任一關鍵字時自動回覆；沒對到的訊息不回，留給你手動聊天。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "line-replies".
 */
export interface LineReply {
  id: number;
  /**
   * 只給你自己看，例如「報價」
   */
  title: string;
  /**
   * 用逗號分隔，例如：報價,價格,多少錢
   */
  keywords: string;
  reply: string;
  buttonLabel?: string | null;
  /**
   * 可填網站路徑，例如 /contact
   */
  buttonUrl?: string | null;
  enabled?: boolean | null;
  /**
   * 數字小的排前面
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "line-sessions".
 */
export interface LineSession {
  id: number;
  userId: string;
  displayName?: string | null;
  step: number;
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * 客戶用這個 Google 帳號登入「客戶專區」查看與支付帳單
   */
  email: string;
  contact?: string | null;
  site?: string | null;
  monthlyFee?: number | null;
  billingDay?: number | null;
  bills?:
    | {
        month: string;
        amount: number;
        dueDate?: string | null;
        status?: ('unpaid' | 'paid' | 'overdue') | null;
        paymentMethod?: ('card' | 'transfer' | 'other') | null;
        paidAt?: string | null;
        /**
         * 刷卡時自動產生
         */
        tradeNo?: string | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'clients';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'line-replies';
        value: number | LineReply;
      } | null)
    | ({
        relationTo: 'line-sessions';
        value: number | LineSession;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  cover?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tagline?: T;
  problem?: T;
  solution?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  points?:
    | T
    | {
        title?: T;
        description?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        id?: T;
      };
  addons?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedCategories?: T;
  slug?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  siteType?: T;
  industry?: T;
  url?: T;
  year?: T;
  summary?: T;
  tech?:
    | T
    | {
        name?: T;
        id?: T;
      };
  features?:
    | T
    | {
        name?: T;
        id?: T;
      };
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  mobileShot?: T;
  slug?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  lineId?: T;
  source?: T;
  lineUserId?: T;
  service?: T;
  budget?: T;
  message?: T;
  extras?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  status?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "line-replies_select".
 */
export interface LineRepliesSelect<T extends boolean = true> {
  title?: T;
  keywords?: T;
  reply?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "line-sessions_select".
 */
export interface LineSessionsSelect<T extends boolean = true> {
  userId?: T;
  displayName?: T;
  step?: T;
  answers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  contact?: T;
  site?: T;
  monthlyFee?: T;
  billingDay?: T;
  bills?:
    | T
    | {
        month?: T;
        amount?: T;
        dueDate?: T;
        status?: T;
        paymentMethod?: T;
        paidAt?: T;
        tradeNo?: T;
        id?: T;
      };
  note?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroTitle: string;
  heroText?: string | null;
  heroImage?: (number | null) | Media;
  sellingPoints?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  photo?: (number | null) | Media;
  intro?: string | null;
  why?: string | null;
  skills?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  story?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-page".
 */
export interface ProcessPage {
  id: number;
  intro?: string | null;
  steps?:
    | {
        title: string;
        description?: string | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heroTitle?: string | null;
  heroLead?: string | null;
  channelsTitle?: string | null;
  lineNote?: string | null;
  emailNote?: string | null;
  instagramNote?: string | null;
  formTitle?: string | null;
  /**
   * 可以新增、刪除、拖曳排序。留空會使用預設的 7 個欄位。
   */
  fields?:
    | {
        label: string;
        type: 'text' | 'email' | 'tel' | 'textarea' | 'select';
        /**
         * 兩個相鄰的半行欄位會並排
         */
        width?: ('full' | 'half') | null;
        required?: boolean | null;
        /**
         * 同一種最多用一次
         */
        role?: ('other' | 'name' | 'email' | 'phone' | 'lineId' | 'service' | 'budget' | 'message') | null;
        placeholder?: string | null;
        hint?: string | null;
        useServices?: boolean | null;
        /**
         * 一行一個選項
         */
        options?: string | null;
        /**
         * 例如：還不確定
         */
        emptyOption?: string | null;
        id?: string | null;
      }[]
    | null;
  requireContact?: boolean | null;
  contactHint?: string | null;
  requireContactMessage?: string | null;
  submitLabel?: string | null;
  successTitle?: string | null;
  successText?: string | null;
  errorText?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  lineId?: string | null;
  /**
   * 例如 https://line.me/ti/p/~yourid
   */
  lineUrl?: string | null;
  email?: string | null;
  /**
   * 不含 @
   */
  instagram?: string | null;
  serviceArea?: string | null;
  footerBlurb?: string | null;
  footerKeywords?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaButton?: string | null;
  bankName?: string | null;
  bankCode?: string | null;
  bankAccount?: string | null;
  bankAccountName?: string | null;
  paymentNote?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "line-settings".
 */
export interface LineSetting {
  id: number;
  /**
   * 留空就不送
   */
  welcomeMessage?: string | null;
  /**
   * 用你自己的 LINE 傳下方的綁定指令給官方帳號，會自動填入
   */
  adminUserId?: string | null;
  /**
   * 用你的 LINE 把這整句傳給官方帳號
   */
  bindCommand?: string | null;
  /**
   * 客人按圖文選單「線上詢價」或傳「詢價」後，依序一題一題問。問完會自動建立一張詢問單並通知你。
   */
  inquirySteps?:
    | {
        question: string;
        /**
         * 用逗號分隔，會變成可以直接點的按鈕，例如：形象網站,購物網站,還不確定
         */
        options?: string | null;
        saveTo?: ('message' | 'service' | 'budget') | null;
        id?: string | null;
      }[]
    | null;
  inquiryIntro?: string | null;
  inquiryDone?: string | null;
  notifyInquiry?: boolean | null;
  notifyPayment?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroText?: T;
  heroImage?: T;
  sellingPoints?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  photo?: T;
  intro?: T;
  why?: T;
  skills?:
    | T
    | {
        name?: T;
        id?: T;
      };
  story?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-page_select".
 */
export interface ProcessPageSelect<T extends boolean = true> {
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        duration?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroLead?: T;
  channelsTitle?: T;
  lineNote?: T;
  emailNote?: T;
  instagramNote?: T;
  formTitle?: T;
  fields?:
    | T
    | {
        label?: T;
        type?: T;
        width?: T;
        required?: T;
        role?: T;
        placeholder?: T;
        hint?: T;
        useServices?: T;
        options?: T;
        emptyOption?: T;
        id?: T;
      };
  requireContact?: T;
  contactHint?: T;
  requireContactMessage?: T;
  submitLabel?: T;
  successTitle?: T;
  successText?: T;
  errorText?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  lineId?: T;
  lineUrl?: T;
  email?: T;
  instagram?: T;
  serviceArea?: T;
  footerBlurb?: T;
  footerKeywords?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  ctaButton?: T;
  bankName?: T;
  bankCode?: T;
  bankAccount?: T;
  bankAccountName?: T;
  paymentNote?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "line-settings_select".
 */
export interface LineSettingsSelect<T extends boolean = true> {
  welcomeMessage?: T;
  adminUserId?: T;
  bindCommand?: T;
  inquirySteps?:
    | T
    | {
        question?: T;
        options?: T;
        saveTo?: T;
        id?: T;
      };
  inquiryIntro?: T;
  inquiryDone?: T;
  notifyInquiry?: T;
  notifyPayment?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}